### ISSUE TITLE
Add software license

### ISSUE THREAD

**Issue by spiffytech** [fogzot/vroomjs#6]
Please add a software license to this project. I'd like to use it at my workplace, but the lawyers are picky. 

Since it doesn't already have a license, I assume you're happy with "do whatever you want with it" license terms. If so, BSD or Apache would be a good choice.

**Comment by fogzot** [comment]
Just have a look at any source code file: each has the license text in it.
If you still need it just copy that into a LICENSE file and submit a pull request. ;)
